### ISSUE TITLE
missing close icon on document tabs

### ISSUE THREAD

**Issue by easyw** [pgilfernandez/FreeCAD_Blender-stylesheet#1]
Hi,
I tested this theme on Qt5 and it seems I miss the close icon
![blender-missing-close-img](https://user-images.githubusercontent.com/3032347/61358122-eea7e300-a879-11e9-89a0-e5ef0c85e4a9.png)
tested on OS: Windows 10 Version: 0.19.17352 (Git)
Python version: 3.6.6, Qt version: 5.6.2, Coin version: 4.0.0a, OCC version: 7.3.0

**Comment by pgilfernandez** [comment]
Solved!

**Comment by easyw** [comment]
Thx!
